# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  

- task: SplitUpdateDefinition@4
  inputs:
    ServiceConnection: 'SplitADOExperi'
    WorkspaceId: 'd28a9ae0-fe3a-11ec-a40c-36bbbb172e18'
    EnvironmentId: 'd2980860-fe3a-11ec-a40c-36bbbb172e18'
    SplitTargetingDefinition: |
      {
        "treatments": [
          {
            "name": "on"
          },
          {
            "name": "off"
          }
        ],
        "defaultTreatment": "off",
        "rules": [],
        "defaultRule": [
          {
            "treatment": "off",
            "size": 100
          }
        ]
      }